version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'artc-webserver'
    networks:
      artc_network:
       ipv4_address: 172.28.1.4
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'artc-mysql'
    networks:
     artc_network:
       ipv4_address: 172.28.1.5
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: dbArtc
      MYSQL_USER: artc
      MYSQL_PASSWORD: artc
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'artc-phpmyadmin'
    networks:
     artc_network:       
      ipv4_address: 172.28.1.2
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'artc-redis'
    image: redis:latest
    networks:
     artc_network:
      ipv4_address: 172.28.1.3
    ports:
      - "6379:6379"
networks:
  artc_network:
   ipam:
    config:
     - subnet: 172.28.1.1/24

